name: pro_m_esp_smartconfig
description: EspTouch and EspTouchV2 implementations of SmartConfig provisioning protocols. Plain Dart. All platforms.
version: 3.0.0
homepage: https://mavinsandeep.xyz
repository: https://github.com/userdevil/Pro_M_Smart_config

environment:
  sdk: '^3.4.0'

dependencies: 
  logging: ^1.3.0
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
